# See https://docs.wandb.com/sweeps/configuration
program: main.py
command:
  - python
  - ${program}
  - --no-es
  - --individ-indx-seqs
  - ${args}
method: grid
metric:
  name: test_acc
  goal: maximize
parameters:
  max-epochs:
    values: [40]
  chkpt-epochs:
    values: [100]
  model-type:
    values: ["CondNet"] #  Net CondNet  simpleCNN2 SparseNet
  dataset:
    values: ["svhn_resnet18"] # MNIST  CIFAR10  FashionMNIST  cifar100_resnet50  svhn_resnet18
  # train-subset-size:
  #   values: [1000]
  make-linear:
    values: ["False"]
  mbs:
    values: [50]
  lr:
    values: [0.01]
  lr-decay:
    values: ["none"] # cosine  none
  num-layers:
    values: [4]
  num-mid:
    values: [32]
  # fan-in:
  #   values: [32]
  fan-out-const:
    values: ["False"]
  sparsity-type:
    values: ["per_neuron"] #, "per_layer"
  connect-type:
    values: ["scattered"]
  seed:
    values: [101] #,104,105,106,107,108,109,110]