# Hacks until we have compose installed:
# docker build --file ./Dockerfile -t rigl-sweep-agent .
# docker create --cpus 12 --memory 30G --env-file .env --gpus '"device=1"' -i -t rigl-sweep-agent:latest
# docker create --env-file .env --gpus '"device=0"' -i -t rigl-sweep-agent:latest
# docker run --cpus 12 --memory 30G --env-file .env --gpus '"device=0"' -i -t --name gpu-0 rigl-sweep-agent:latest
# docker run --cpus 12 --memory 30G --env-file .env --gpus '"device=1"' -i -t -d --name gpu-1 rigl-sweep-agent:latest
# docker run --cpus 12 --memory 30G --env-file .env --gpus '"device=2"' -i -t --name gpu-2 rigl-sweep-agent:latest
# docker run --cpus 12 --memory 30G --env-file .env --gpus '"device=3"' -i -t --name gpu-3 rigl-sweep-agent:latest
# docker run -itd --env-file ./.env --mount source=/home/mike/condensed-sparsity,target=/home/condensed-sparisty,type=bind --mount source=/datasets/ILSVRC2012,target=/datasets/ILSVRC2012,type=bind --mount source=/scratch/datasets/ILSVRC2012,target=/scratch/datasets/ILSVRC2012,type=bind --gpus all --shm-size 16G --name cond-rigl-dev ac605476a22f

services:
  sweep_agent:
    build: .
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]
              driver: nvidia
              count: 1
        limits:
          cpus: ${CPUS_LIMIT}
          memory: ${MEMORY_LIMIT}
