services:
  sweep-agent:
    build:
      context: ./
      dockerfile: ./Dockerfile
      shm_size: 16G
    image: rigl-agent
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]
              driver: nvidia
              count: 1
        limits:
          cpus: 12
          memory: 30G
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - type: bind
        source: /scratch/datasets/ILSVRC2012
        target: /scratch/datasets/ILSVRC2012
      - type: bind
        source: /home/mike/condensed-sparsity
        target: /home/user/condensed-sparsity
