# [project]
# name = "TBD"
# version ="0.1"
# authors = []
# homepage = "https://github.com/calgaryml/condensed-sparsity/"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
exclude ='''
/(

    examples/utils.py
    | examples/main.py
    | examples/models.py
)
'''

[tool.pytest.ini_options]
pythonpath = [
    ".", "src", "tests",
]
addopts = "--cov src --cov-report html --cov-branch --import-mode importlib"
markers = [
    "integration",
    "slow"
]
norecursedirs = "tests/utils"
testpaths = "tests"
