defaults:
  - dataset: cifar10
  - model: wide_resnet22
  - _self_

experiment:
  comment: dense_alloc-${rigl.dense_allocation}_weight_per_neuron-${rigl.min_salient_weights_per_neuron}
  name: ${model.name}_${dataset.name}_${experiment.comment}
  resume_from_checkpoint: False
  run_id: null

paths:
  base: ${oc.env:BASE_PATH}
  data_folder: ${paths.base}/data
  artifacts: ${paths.base}/artifacts
  logs: ${paths.base}/logs
  checkpoints: ${paths.artifacts}/checkpoints

rigl: 
  # percentage of dense parameters allowed. if null, pruning will not 
  # be used. must be on the interval (0, 1]
  dense_allocation: 0.01
  # number of steps between rigl pruning / regrow iterations
  delta: 100  # 4096 * 100 / 512 = 800
  # number of gradients to accumulate before scoring for rigl -> Based on simulated batch step number!
  grad_accumulation_n: 8  # 4096 / 512 without simulated batch size, 1 otheriwse
  # alpha param for pruning for cosine decay in determining how many connections to prune/regrow
  alpha: 0.3  # 0.3 for vanilla rigl, 0.5 for ITOP -> Inital fraction of weights to update every pruner step
  # if 1, use random sparsity topo and remain static
  static_topo: 0
  # If True, use const_fan_in scheduler.
  const_fan_in: True
  # Define layer-wise sparsity distribution. Options include `uniform` & `erk`
  sparsity_distribution: erk
  # Power scale for ERK distribution
  erk_power_scale: 1.0
  # Use T_end from vanilla rigl, if False, explore new topologies until end of training
  use_t_end: True
  # Static ablation, if true, ablate filters at init with static mask. 
  static_ablation: False
  # Dyanmic ablation will ablate filters dynamically during traing based on gradient information. Cannot be True if static_ablation is True
  dynamic_ablation: True
  # Filter abalation threshold criterion
  filter_ablation_threshold: 0.01 # 1%
  # If True, update weight initalization to account for sparse const fan in. 
  use_sparse_initialization: False ## TODO!
  # Param for minimum number of salient weights per neuron. If < this value, the neuron will be dynamically ablated. 
  min_salient_weights_per_neuron: 2

training:
  # quickly check a single pass",
  dry_run: False
  # batch size for training
  batch_size: 128  # 128 for cifar10, multiples of 256 for imagenet w/ scaled lr
  # Batch size to simulate by taking multiple steps per optimizer update (accumulate grads)
  simulated_batch_size: null
  # batch size for testing
  test_batch_size: 1000
  # number of epochs to train
  epochs: 250  # For imagenet, training will finish at ~ epoch 102.31, use 250 for cifar10
  # random seed
  seed: 42
  # Log interval (number of mini-batch steps)
  log_interval: 1000
  # For Saving the current Model
  save_model: True
  # max number of steps (will override epochs) -> Based on mini-batch steps (NOT SIMULATED BATCHES!)
  max_steps: null  # 4096 * 32000 / 512 = 256000 from rigl paper

  ## Optimization
  optimizer: sgd # "sgd", "adamw"
  # L2 Regularization for optimizer
  weight_decay: 0.0005  # 5.0e-4 -> cifar10   0.0001 -> imagenet
  # Momentum coefficient for SGD optimizer
  momentum: 0.9  # 0.9 -> rigl value
  # Label smoothing for cross entropy
  label_smoothing: 0.0  # 0.1 for imagenet, 0.0 or null for cifar


  ## Scheduler
  scheduler: step_lr # cosine_annealing_with_warm_up, step_lr_with_warm_up
  # Learning rate after warmup
  lr: 0.1  # 0.1 * batch size / 256 per original paper -> Use 1.6 for 4096 simulated batch size. 0.1 for ITOP
  # Learning rate for first epoch of warm up, only applies to schedulers with linear warm up
  init_lr: 1.0e-6
  # Number of epochs to warm up for linear warm ups
  warm_up_steps: 0
  # Learning rate step gamma
  gamma: 0.5  # 0.1 for imagenet, 0.5 for cifar
  # Step size to use in learning rate scheduler if StepLR is used. List[int] || int
  step_size: 77  # Imagenet -> [30,70,90] TODO: Convert to cifar 10 -> every 30,000 mini-batch steps ~= 77 epochs


compute:
  # disables CUDA training",
  no_cuda: False
  cuda_kwargs: 
    num_workers: ${ oc.decode:${oc.env:NUM_WORKERS} }  # decode casts to int
    pin_memory: True
  # If True, use data-parallelization model for distributed training
  distributed: False
  # Number of CUDA devices to use for distributed training
  world_size: 2
  # Backend to use for distributed training, options: ["nccl", "gloo"]
  dist_backend: "nccl"

wandb:
  project: condensed-rigl
  entity: condensed-sparsity
  start_method: thread
  log_images: False
  watch_model_grad_and_weights: False
  log_filter_stats: True

hydra:  
  run:
    dir: ${paths.logs}
