defaults:
  - dataset: imagenet
  - model: resnet50
  - _self_

experiment:
  comment: ${rigl.dense_allocation}_${rigl.const_fan_in}_dist_test
  name: ${model.name}_${dataset.name}_${experiment.comment}
  resume_from_checkpoint: False
  run_id: null

paths:
  base: ${oc.env:BASE_PATH}
  data_folder: ${paths.base}/data
  artifacts: ${paths.base}/artifacts
  logs: ${paths.base}/logs
  checkpoints: ${paths.artifacts}/checkpoints

rigl: 
  # percentage of dense parameters allowed. if None, pruning will not 
  # be used. must be on the interval (0, 1]
  dense_allocation: 0.1
  # delta param for pruning
  delta: 100
  # number of gradients to accumulate before scoring for rigl
  grad_accumulation_n: 1
  # alpha param for pruning for cosine decay in determining how many connections to prune/regrow
  alpha: 0.3
  # if 1, use random sparsity topo and remain static
  static_topo: 0
  # If True, use const_fan_in scheduler.
  const_fan_in: True
  # Define layer-wise sparsity distribution. Options include `uniform` & `erk`
  sparsity_distribution: erk
  # Power scale for ERK distribution
  erk_power_scale: 1.0

training:
  # quickly check a single pass",
  dry_run: False
  # input batch size for testing
  batch_size: 512
  # number of epochs to train
  test_batch_size: 1024
  # number of epochs to train
  epochs: 102
  # random seed
  seed: 42
  # Log interval (number of steps / iterations)
  log_interval: 100
  # For Saving the current Model
  save_model: True
  # max number of steps (will override epochs)
  max_steps: null

  ## Optimization
  optimizer: sgd # "sgd", "adamw"
  # L2 Regularization for optimizer
  weight_decay: 0.0001  # 5.0e-4 -> cifar10
  # Momentum coefficient for SGD optimizer
  momentum: 0.9  # 0.9 -> rigl value


  ## Scheduler
  scheduler: step_lr # cosine_annealing_with_warm_up, step_lr_with_warm_up
  # Learning rate after warmup (default: 0.01)",
  lr: 0.1
  # Learning rate for first epoch of warm up, only applies to schedulers with linear warm up
  init_lr: 0
  # Number of steps to warm up for linear warm ups
  warm_up_steps: 5
  # Learning rate step gamma
  gamma: 0.2
  # Step size to use in learning rate scheduler if StepLR is used.
  step_size: 75000 # imagenet -> ~ every 30 epochs ( (1281167 / batch_size) * 30 )   # cifar10 -> 30000


compute:
  # disables CUDA training",
  no_cuda: False
  cuda_kwargs: 
    num_workers: ${ oc.decode:${oc.env:NUM_WORKERS} }  # decode casts to int
    pin_memory: True
  # If True, use data-parallelization model for distributed training
  distributed: False
  # Number of CUDA devices to use for distributed training
  world_size: 4
  dist_backend: "nccl"

wandb:
  project: condensed-rigl
  entity: condensed-sparsity
  start_method: thread

hydra:  
  run:
    dir: ${paths.logs}
