program: train_rigl.py
method: grid
project: condensed-rigl
name: cifar10_min_salient_weights_sweep_with_gamma
metric:
  goal: maximize
  name: accuracy
parameters:
  model:
    values: [resnet18]
  dataset:
    value: cifar10
  rigl.dense_allocation: 
    values: [0.01, 0.05, 0.1, 0.75, 0.5]
      # percentage of dense parameters allowed. if None, pruning will not 
      # be used. must be on the interval (0, 1]
  rigl.const_fan_in: 
    values: [True]
      # If True, use const_fan_in scheduler.
      # sparsity_distribution: erk
      # # Define layer-wise sparsity distribution. Options include `uniform` & `erk`
  rigl.min_salient_weights_per_neuron:
    values: [0,1,2,3,5,7,10]
  training.seed:
    values: [8746, 6037, 7303, 2078, 42]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
