# rigl config group

# number of steps between rigl pruning / regrow iterations
delta: 100 # 4096 * 100 / 512 = 800 || 100 for cifar || x5 -> No change?
# number of gradients to accumulate before scoring for rigl
grad_accumulation_n: 1  # 4096 / 512 without simulated batch size, 1 otheriwse
# Custom topology to use for SkinnyResNet
diet: [17, 16, 17, 14, 16, 33, 31, 31, 32, 30, 65, 63, 63, 65, 63, 122, 124, 124, 114, 125, 0]  # For 99%, 50% saliency
